# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    machine: true

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
    - checkout
    # Download and cache openjdk11
    - restore_cache:
        keys:
        - openjdk-11
    - run:
        name: install openjdk11
        command: |
          if [ ! -d $PWD/jdk-11.0.1 ]
            then
              wget https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_linux-x64_bin.tar.gz
              tar -xvf openjdk-11.0.1_linux-x64_bin.tar.gz
          fi
    - save_cache:
        paths:
        - ~/repo/jdk-11.0.1
        key: openjdk-11

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
    - run: mvn dependency:go-offline
    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}

    - run:
        name: Maven Test
        command: |
          JAVA_HOME=$PWD/jdk-11.0.1 mvn test -D spring.profiles.active=test

